/**
 * Hazmat Envelope — SPARC Phase 1 (PRD §4 Step 2)
 *
 * The Hazmat Envelope is the transport object that carries a raw, flagged payload
 * from the originating RuvBot to MothaShip Core for surgical analysis.
 *
 * Design constraints from PRD:
 *   - status MUST be the literal "contaminated_transit" — any other value is invalid.
 *   - rvf_signature is MANDATORY: PRD §4 Step 2 states "The Hazmat Envelope schema
 *     MUST include the RVF witness hash as a required field."
 *   - An envelope with a missing or empty rvf_signature is treated as an ATTACK VECTOR
 *     (PRD §4 Step 4): "An unauthenticated contaminated_transit claim is an attack
 *     vector itself." Such envelopes MUST NOT bypass Layer 1.
 *   - payload is base64-encoded (RFC 4648 §4 standard, NOT URL-safe) to prevent
 *     JIT execution at the edge (PRD §5 HONESTCUE).
 *
 * Validation at MothaShip ingress (PRD §4 Step 4):
 *   1. Parse with HazmatEnvelopeSchema.safeParse() — structural check (this schema).
 *   2. Verify rvf_signature against the RVF Witness Chain — cryptographic check.
 *      The witness hash MUST cover the canonicalized full envelope:
 *      status + payload + metadata.source_node_id + metadata.created_at.
 *   3. Confirm source_node_id is a registered, trusted RuvBot.
 *   4. Enforce timestamp freshness: reject envelopes with created_at older than
 *      ~5 minutes or dated more than 60 seconds in the future. Use
 *      validateFreshness() exported below.
 *   Only envelopes passing ALL FOUR checks bypass Layer 1 for Core Surgery.
 *
 * This schema covers Step 1 (structural). Steps 2-3 are implemented in
 * MothaShip ingress logic (future integration phase).
 */

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Zod schema (single source of truth — TypeScript types are derived from this)
// ---------------------------------------------------------------------------

/** Maximum payload size: 64 KiB base64-encoded (~48 KiB decoded). */
const MAX_PAYLOAD_B64_CHARS = 87384; // ceil(65536 / 3) * 4

const NULL_HASH_64 = '0'.repeat(64);

export const HazmatEnvelopeSchema = z.object({
  /**
   * Transport status — always "contaminated_transit" for envelopes in transit
   * to MothaShip Core.  The literal constraint prevents any envelope with a
   * different status value from passing structural validation.
   */
  status: z.literal('contaminated_transit'),

  /**
   * Base64-encoded raw content, as wrapped by RuvBot (PRD §4 Step 2).
   * Encoding: RFC 4648 §4 standard base64 (uses +/ not -_). NOT URL-safe.
   * Base64 encoding neutralises JIT execution risk at the edge (PRD §5 HONESTCUE).
   * Must be non-empty and ≤ 64 KiB decoded to prevent memory-exhaustion DoS.
   */
  payload: z
    .string()
    .min(1, 'Payload must not be empty')
    .max(MAX_PAYLOAD_B64_CHARS, `Payload exceeds maximum size (${MAX_PAYLOAD_B64_CHARS} base64 chars)`)
    .refine(
      s => /^[A-Za-z0-9+/]*={0,2}$/.test(s),
      'Payload must use valid standard base64 characters (RFC 4648 §4)',
    )
    .refine(
      s => s.length % 4 === 0,
      'Payload length must be a multiple of 4 (valid base64 encoding)',
    ),

  /**
   * RVF PROVENANCE witness hash generated by the originating RuvBot
   * (PRD §4 Step 2: "records a cryptographic RVF PROVENANCE witness entry").
   *
   * Format: SHA-256 hex digest, 64 lowercase hex characters.
   * Scope: MUST cover canonicalized full envelope content
   *   (status + payload + metadata.source_node_id + metadata.created_at).
   *
   * SECURITY: An empty, null (all-zeros), or malformed rvf_signature is an
   * attack vector (PRD §4 Step 4). Structural validation here catches format
   * violations; cryptographic verification against the RVF Witness Chain
   * happens at MothaShip ingress (Step 2).
   */
  rvf_signature: z
    .string()
    .length(64, 'RVF PROVENANCE witness hash must be exactly 64 hex characters (SHA-256)')
    .regex(/^[a-f0-9]{64}$/, 'RVF PROVENANCE witness hash must be lowercase hexadecimal — malformed signature is an attack vector')
    .refine(
      s => s !== NULL_HASH_64,
      'Null hash (all-zeros) is not a valid RVF PROVENANCE signature',
    )
    .refine(
      s => {
        // Reject low-entropy degenerate hashes (e.g. 'a'.repeat(64), 'f'.repeat(64)).
        // A genuine SHA-256 output will never have a single character dominating ≥60/64 positions.
        const counts = new Map<string, number>();
        for (const c of s) counts.set(c, (counts.get(c) ?? 0) + 1);
        return Math.max(...counts.values()) < 60;
      },
      'RVF signature has insufficient entropy — degenerate hash patterns are not valid',
    ),

  /**
   * Provenance metadata for audit trail (PRD §8) and trusted-node verification
   * (PRD §4 Step 4: "known and trusted RuvBots").
   */
  metadata: z.object({
    /**
     * ISO 8601 datetime of encapsulation at the edge node (UTC only — no offset).
     * Schema validates format only. MothaShip ingress MUST call validateFreshness()
     * to enforce: reject envelopes older than ~5 minutes or >60s in the future,
     * preventing replay attacks with captured envelopes.
     */
    created_at: z.string().datetime({ offset: false, message: 'created_at must be a valid ISO 8601 UTC datetime (no timezone offset)' }),

    /**
     * Identifier of the originating RuvBot node (max 128 chars).
     * MothaShip ingress uses this to verify the node is in the trusted registry
     * before accepting bypass-Layer-1 routing. Format is deployment-specific;
     * tighten this constraint once the node ID scheme is finalised.
     */
    source_node_id: z
      .string()
      .min(1, 'source_node_id is required for provenance verification')
      .max(128, 'source_node_id must not exceed 128 characters'),
  }),
});

// ---------------------------------------------------------------------------
// Derived TypeScript types
// ---------------------------------------------------------------------------

/** Inferred TypeScript type from HazmatEnvelopeSchema (Zod is the source of truth). */
export type HazmatEnvelope = z.infer<typeof HazmatEnvelopeSchema>;

/**
 * Shape-only type alias for consumers that need the type without importing Zod runtime
 * (e.g. mock-ruvbot.ts, test fixtures).
 *
 * This is structurally identical to HazmatEnvelope — the name "Shape" signals that
 * this type carries NO runtime enforcement. TypeScript erases all constraints at
 * compile time, so any object literal that satisfies the structural shape passes the
 * type checker regardless of how it was constructed.
 *
 * MANDATORY: every consumer receiving a HazmatEnvelopeShape from an untrusted source
 * MUST re-validate through HazmatEnvelopeSchema.safeParse() before processing.
 * The type is not a trust boundary; the schema is.
 */
export type HazmatEnvelopeShape = HazmatEnvelope;

/** @deprecated Use HazmatEnvelopeShape. Kept for backwards compatibility. */
export type IHazmatEnvelope = HazmatEnvelopeShape;

// ---------------------------------------------------------------------------
// Freshness validator (MothaShip ingress Step 4)
// ---------------------------------------------------------------------------

/**
 * Validate that an envelope's created_at timestamp falls within the acceptable
 * freshness window. Call this at MothaShip ingress after structural parsing.
 *
 * @param envelope   A structurally-valid HazmatEnvelope (passed HazmatEnvelopeSchema.parse).
 * @param windowMs   Maximum age in milliseconds (default: 5 minutes).
 * @param futureMs   Maximum future tolerance in milliseconds (default: 60 seconds).
 * @returns true if fresh, false if stale or future-dated (replay attack indicator).
 */
export function validateFreshness(
  envelope: HazmatEnvelope,
  windowMs = 300_000,
  futureMs = 60_000,
): boolean {
  const now = Date.now();
  const ts  = new Date(envelope.metadata.created_at).getTime();
  return ts >= now - windowMs && ts <= now + futureMs;
}

// ---------------------------------------------------------------------------
// Factory helper (for RuvBot envelope construction)
// ---------------------------------------------------------------------------

/**
 * Construct a validated HazmatEnvelope from raw parts.
 * Throws a ZodError if any field fails validation.
 * Intended for use by RuvBot when wrapping a flagged payload (PRD §4 Step 2).
 *
 * @param rawPayload    The raw flagged content — caller must base64-encode it first
 *                      using standard RFC 4648 §4 encoding (not URL-safe).
 * @param rvfSignature  RVF PROVENANCE witness hash (SHA-256 hex, lowercase 64 chars)
 *                      from the RVF Witness Chain entry. Must cover full envelope content.
 * @param sourceNodeId  Identifier of the RuvBot creating this envelope (max 128 chars).
 */
export function createHazmatEnvelope(
  rawPayload:   string,
  rvfSignature: string,
  sourceNodeId: string,
): HazmatEnvelope {
  return HazmatEnvelopeSchema.parse({
    status:        'contaminated_transit',
    payload:       rawPayload,
    rvf_signature: rvfSignature.toLowerCase(),
    metadata: {
      created_at:     new Date().toISOString(),
      source_node_id: sourceNodeId,
    },
  });
}
