/**
 * Journalism Report — RuvBot field dispatch to MothaShip
 *
 * A JournalismReport carries the output of a RuvBot "interview" with a
 * resident bot in an agent city (e.g. Moltbook). The report is submitted to
 * the MothaShip via POST /api/v1/reports/dispatch after the RuvBot's local
 * aidefence layer has sanitized the content.
 *
 * Format rationale — "beads":
 *   Interview exchanges are heterogeneous: text turns, observations, metadata
 *   snippets, and structured insights may all appear. Rather than locking a
 *   rigid content schema before any real RuvBot has been deployed, each
 *   exchange is represented as a discrete JSON bead in a sequence. The
 *   MothaShip stores the bead array verbatim; downstream analysis (Surgeon,
 *   corpus builder) interprets bead content.
 *
 *   // WIRE-IN: tighten JsonBead.content union type once the first live RuvBot
 *   // interview format is observed in production. Do not guess in advance.
 *
 * Security note:
 *   The MothaShip runs the full 4-layer AIMDS stack on all inbound traffic,
 *   including /api/v1/reports/dispatch. A JournalismReport arriving at this
 *   endpoint is NOT trusted by default — it passes through Layers 1–4 before
 *   being stored. The source_node_id is verified against the trusted-node
 *   registry at ingress (same as HazmatEnvelope processing).
 */

import { z } from 'zod';
import { randomUUID } from 'node:crypto';

// ---------------------------------------------------------------------------
// JsonBead — a single discrete unit in the interview sequence
// ---------------------------------------------------------------------------

/**
 * Known bead types. Extensible — unknown types are accepted and stored as-is.
 * Tighten this union once production interview formats are observed.
 */
export const BEAD_TYPES = ['exchange', 'observation', 'metadata', 'structural_insight'] as const;
export type BeadType = typeof BEAD_TYPES[number] | string;

export const JsonBeadSchema = z.object({
  /**
   * Zero-based sequence number. Beads MUST be ordered; the MothaShip
   * rejects reports where seq values are non-contiguous or non-monotonic.
   */
  seq: z.number().int().nonnegative('seq must be a non-negative integer'),

  /**
   * Bead type tag. Use known BEAD_TYPES where possible; arbitrary strings
   * are accepted for forward compatibility.
   */
  type: z.string().min(1, 'bead type must not be empty').max(64, 'bead type exceeds 64 characters'),

  /**
   * Bead content — intentionally untyped at this stage.
   * // WIRE-IN: replace z.unknown() with a discriminated union keyed on `type`
   * // once real RuvBot interview formats are observed in production.
   */
  content: z.unknown(),
});

export type JsonBead = z.infer<typeof JsonBeadSchema>;

// ---------------------------------------------------------------------------
// JournalismReportSchema — full report envelope
// ---------------------------------------------------------------------------

/** Maximum number of beads per report (prevents memory-exhaustion DoS). */
const MAX_BEADS = 1000;

/** Maximum length for free-text string fields. */
const MAX_ID_LENGTH = 128;

export const JournalismReportSchema = z.object({
  /**
   * Unique report identifier — UUID v4, generated by the RuvBot at dispatch
   * time. Used for idempotent re-submission (MothaShip deduplicates on this).
   */
  report_id: z
    .string()
    .uuid('report_id must be a valid UUID v4'),

  /**
   * Identifier of the RuvBot that conducted the interview and filed this
   * report. Verified against the trusted-node registry at MothaShip ingress.
   */
  source_node_id: z
    .string()
    .min(1, 'source_node_id is required')
    .max(MAX_ID_LENGTH, `source_node_id must not exceed ${MAX_ID_LENGTH} characters`),

  /**
   * Identifier of the resident bot that was interviewed (Moltbook profile ID
   * or equivalent agent-city identifier).
   */
  moltbook_profile_id: z
    .string()
    .min(1, 'moltbook_profile_id is required')
    .max(MAX_ID_LENGTH, `moltbook_profile_id must not exceed ${MAX_ID_LENGTH} characters`),

  /**
   * ISO 8601 UTC datetime at which the RuvBot submitted this report.
   * MothaShip ingress enforces a freshness window (same as HazmatEnvelope):
   * reject reports older than 5 minutes or more than 60 seconds in the future.
   */
  submitted_at: z
    .string()
    .datetime({ offset: false, message: 'submitted_at must be a valid ISO 8601 UTC datetime (no timezone offset)' }),

  /**
   * The interview as an ordered sequence of JSON beads.
   * Must contain at least one bead; capped at MAX_BEADS to prevent DoS.
   * seq values must be contiguous starting from 0.
   */
  beads: z
    .array(JsonBeadSchema)
    .min(1, 'A report must contain at least one bead')
    .max(MAX_BEADS, `A report must not exceed ${MAX_BEADS} beads`)
    .refine(
      beads => beads.every((b, i) => b.seq === i),
      'Bead seq values must be contiguous integers starting from 0',
    ),
});

export type JournalismReport = z.infer<typeof JournalismReportSchema>;

// ---------------------------------------------------------------------------
// Factory helper (for RuvBot report construction)
// ---------------------------------------------------------------------------

/**
 * Construct a validated JournalismReport from raw parts.
 * Throws a ZodError if any field fails validation.
 *
 * @param sourceNodeId       Identifier of the dispatching RuvBot.
 * @param moltbookProfileId  Resident bot identifier from the agent city.
 * @param beads              Ordered interview beads — seq must start at 0.
 */
export function createJournalismReport(
  sourceNodeId: string,
  moltbookProfileId: string,
  beads: Omit<JsonBead, 'seq'>[],
): JournalismReport {
  return JournalismReportSchema.parse({
    report_id:           randomUUID(),
    source_node_id:      sourceNodeId,
    moltbook_profile_id: moltbookProfileId,
    submitted_at:        new Date().toISOString(),
    beads:               beads.map((b, i) => ({ ...b, seq: i })),
  });
}
