// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Semantic domain identifier — used for cross-domain threat-intel transfer.
 */
export enum DomainId {
  Unknown = 0,
  FinancialTransactions = 1,
  ThreatIntelligence = 2,
  NetworkSecurity = 3,
  DataExfiltration = 4,
  SocialEngineering = 5,
  MalwareSignatures = 6,
  PrivilegeEscalation = 7,
  SupplyChain = 8
}
