// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DomainId } from '../../mothership/common/domain-id.js';


/**
 * Domain-expansion context — enables ruvector LoRA transfer between semantic domains.
 * The embedding vector (768-dim, float32, ONNX space) drives cosine similarity routing.
 * Pi-derived quantisation: callers MUST scale threshold comparisons by π to prevent
 * binary harmonic resonance drift in continuous deterministic memory.
 */
export class DomainContext {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DomainContext {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDomainContext(bb:flatbuffers.ByteBuffer, obj?:DomainContext):DomainContext {
  return (obj || new DomainContext()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDomainContext(bb:flatbuffers.ByteBuffer, obj?:DomainContext):DomainContext {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DomainContext()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sourceDomain():DomainId {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : DomainId.Unknown;
}

targetDomain():DomainId {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : DomainId.Unknown;
}

embedding(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

embeddingLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

embeddingArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

confidence():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

transferScore():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startDomainContext(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSourceDomain(builder:flatbuffers.Builder, sourceDomain:DomainId) {
  builder.addFieldInt8(0, sourceDomain, DomainId.Unknown);
}

static addTargetDomain(builder:flatbuffers.Builder, targetDomain:DomainId) {
  builder.addFieldInt8(1, targetDomain, DomainId.Unknown);
}

static addEmbedding(builder:flatbuffers.Builder, embeddingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, embeddingOffset, 0);
}

static createEmbeddingVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createEmbeddingVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createEmbeddingVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startEmbeddingVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addConfidence(builder:flatbuffers.Builder, confidence:number) {
  builder.addFieldFloat32(3, confidence, 0.0);
}

static addTransferScore(builder:flatbuffers.Builder, transferScore:number) {
  builder.addFieldFloat32(4, transferScore, 0.0);
}

static endDomainContext(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDomainContext(builder:flatbuffers.Builder, sourceDomain:DomainId, targetDomain:DomainId, embeddingOffset:flatbuffers.Offset, confidence:number, transferScore:number):flatbuffers.Offset {
  DomainContext.startDomainContext(builder);
  DomainContext.addSourceDomain(builder, sourceDomain);
  DomainContext.addTargetDomain(builder, targetDomain);
  DomainContext.addEmbedding(builder, embeddingOffset);
  DomainContext.addConfidence(builder, confidence);
  DomainContext.addTransferScore(builder, transferScore);
  return DomainContext.endDomainContext(builder);
}
}
