// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

/**
 * ED25519 signature over (content_digest ‖ timestamp_ns) (64 bytes = 8 × uint64).
 * Required on every provenance-bearing message per Ruv security advisory.
 */
export class Ed25519Signature {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Ed25519Signature {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

b0():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

b1():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

b2():bigint {
  return this.bb!.readUint64(this.bb_pos + 16);
}

b3():bigint {
  return this.bb!.readUint64(this.bb_pos + 24);
}

b4():bigint {
  return this.bb!.readUint64(this.bb_pos + 32);
}

b5():bigint {
  return this.bb!.readUint64(this.bb_pos + 40);
}

b6():bigint {
  return this.bb!.readUint64(this.bb_pos + 48);
}

b7():bigint {
  return this.bb!.readUint64(this.bb_pos + 56);
}

static sizeOf():number {
  return 64;
}

static createEd25519Signature(builder:flatbuffers.Builder, b0: bigint, b1: bigint, b2: bigint, b3: bigint, b4: bigint, b5: bigint, b6: bigint, b7: bigint):flatbuffers.Offset {
  builder.prep(8, 64);
  builder.writeInt64(BigInt(b7 ?? 0));
  builder.writeInt64(BigInt(b6 ?? 0));
  builder.writeInt64(BigInt(b5 ?? 0));
  builder.writeInt64(BigInt(b4 ?? 0));
  builder.writeInt64(BigInt(b3 ?? 0));
  builder.writeInt64(BigInt(b2 ?? 0));
  builder.writeInt64(BigInt(b1 ?? 0));
  builder.writeInt64(BigInt(b0 ?? 0));
  return builder.offset();
}

}
