// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

/**
 * ED25519 public key (32 bytes = 4 × uint64).
 * Vulnerability flag: do NOT use XXH3 alone for origin verification;
 * this key authenticates the originating system via ED25519.
 */
export class Ed25519PublicKey {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Ed25519PublicKey {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

b0():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

b1():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

b2():bigint {
  return this.bb!.readUint64(this.bb_pos + 16);
}

b3():bigint {
  return this.bb!.readUint64(this.bb_pos + 24);
}

static sizeOf():number {
  return 32;
}

static createEd25519PublicKey(builder:flatbuffers.Builder, b0: bigint, b1: bigint, b2: bigint, b3: bigint):flatbuffers.Offset {
  builder.prep(8, 32);
  builder.writeInt64(BigInt(b3 ?? 0));
  builder.writeInt64(BigInt(b2 ?? 0));
  builder.writeInt64(BigInt(b1 ?? 0));
  builder.writeInt64(BigInt(b0 ?? 0));
  return builder.offset();
}

}
