// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Ed25519PublicKey } from '../../mothership/common/ed25519-public-key.js';
import { Ed25519Signature } from '../../mothership/common/ed25519-signature.js';
import { SystemId } from '../../mothership/common/system-id.js';
import { Xxh3Digest } from '../../mothership/common/xxh3-digest.js';


/**
 * Cryptographic provenance record — attaches to every artifact and state change.
 * The signature authenticates the XXH3 content digest; the post-quantum wrapper
 * is applied at the pq-wrap transport layer and is not repeated here.
 */
export class ProvenanceRecord {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProvenanceRecord {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProvenanceRecord(bb:flatbuffers.ByteBuffer, obj?:ProvenanceRecord):ProvenanceRecord {
  return (obj || new ProvenanceRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProvenanceRecord(bb:flatbuffers.ByteBuffer, obj?:ProvenanceRecord):ProvenanceRecord {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProvenanceRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

originSystem():SystemId {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SystemId.Unknown;
}

contentDigest(obj?:Xxh3Digest):Xxh3Digest|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Xxh3Digest()).__init(this.bb_pos + offset, this.bb!) : null;
}

signature(obj?:Ed25519Signature):Ed25519Signature|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Ed25519Signature()).__init(this.bb_pos + offset, this.bb!) : null;
}

publicKey(obj?:Ed25519PublicKey):Ed25519PublicKey|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Ed25519PublicKey()).__init(this.bb_pos + offset, this.bb!) : null;
}

timestampNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

witnessChainHeight():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startProvenanceRecord(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addOriginSystem(builder:flatbuffers.Builder, originSystem:SystemId) {
  builder.addFieldInt8(0, originSystem, SystemId.Unknown);
}

static addContentDigest(builder:flatbuffers.Builder, contentDigestOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, contentDigestOffset, 0);
}

static addSignature(builder:flatbuffers.Builder, signatureOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, signatureOffset, 0);
}

static addPublicKey(builder:flatbuffers.Builder, publicKeyOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, publicKeyOffset, 0);
}

static addTimestampNs(builder:flatbuffers.Builder, timestampNs:bigint) {
  builder.addFieldInt64(4, timestampNs, BigInt('0'));
}

static addWitnessChainHeight(builder:flatbuffers.Builder, witnessChainHeight:bigint) {
  builder.addFieldInt64(5, witnessChainHeight, BigInt('0'));
}

static endProvenanceRecord(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
