// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Outcome status for RPC calls and gateway responses.
 */
export enum RequestStatus {
  Pending = 0,
  Approved = 1,
  Denied = 2,
  Escalated = 3,
  Timeout = 4
}
