// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Identifies which system produced or consumed a message.
 */
export enum SystemId {
  Unknown = 0,
  WasmSecurityGate = 1,
  UnixAdaptiveSentinel = 2,
  L3ApiGateway = 3
}
