// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Severity classification for threats and policy decisions.
 */
export enum ThreatLevel {
  None = 0,
  Low = 1,
  Medium = 2,
  High = 3,
  Critical = 4
}
