// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Serialisation format used at a boundary crossing.
 * JSON is strictly forbidden at the WASM/Unix boundary (ADR-026).
 */
export enum TransportEncoding {
  FlatBuffers = 0,
  MessagePack = 1
}
