// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Ed25519PublicKey } from '../../mothership/common/ed25519-public-key.js';
import { Ed25519Signature } from '../../mothership/common/ed25519-signature.js';
import { SystemId } from '../../mothership/common/system-id.js';
import { Xxh3Digest } from '../../mothership/common/xxh3-digest.js';


/**
 * Single entry in the append-only RVF Witness Chain.
 * Signed by the authoring system; the pq_signature field carries the
 * post-quantum wrapper from the Decoupled Hardware CA (optional at chain bootstrap).
 */
export class WitnessEntry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WitnessEntry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWitnessEntry(bb:flatbuffers.ByteBuffer, obj?:WitnessEntry):WitnessEntry {
  return (obj || new WitnessEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWitnessEntry(bb:flatbuffers.ByteBuffer, obj?:WitnessEntry):WitnessEntry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WitnessEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

height():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

prevDigest(obj?:Xxh3Digest):Xxh3Digest|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Xxh3Digest()).__init(this.bb_pos + offset, this.bb!) : null;
}

payloadDigest(obj?:Xxh3Digest):Xxh3Digest|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Xxh3Digest()).__init(this.bb_pos + offset, this.bb!) : null;
}

signature(obj?:Ed25519Signature):Ed25519Signature|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Ed25519Signature()).__init(this.bb_pos + offset, this.bb!) : null;
}

publicKey(obj?:Ed25519PublicKey):Ed25519PublicKey|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Ed25519PublicKey()).__init(this.bb_pos + offset, this.bb!) : null;
}

timestampNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

author():SystemId {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SystemId.Unknown;
}

pqSignature(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

pqSignatureLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

pqSignatureArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startWitnessEntry(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addHeight(builder:flatbuffers.Builder, height:bigint) {
  builder.addFieldInt64(0, height, BigInt('0'));
}

static addPrevDigest(builder:flatbuffers.Builder, prevDigestOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, prevDigestOffset, 0);
}

static addPayloadDigest(builder:flatbuffers.Builder, payloadDigestOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, payloadDigestOffset, 0);
}

static addSignature(builder:flatbuffers.Builder, signatureOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, signatureOffset, 0);
}

static addPublicKey(builder:flatbuffers.Builder, publicKeyOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, publicKeyOffset, 0);
}

static addTimestampNs(builder:flatbuffers.Builder, timestampNs:bigint) {
  builder.addFieldInt64(5, timestampNs, BigInt('0'));
}

static addAuthor(builder:flatbuffers.Builder, author:SystemId) {
  builder.addFieldInt8(6, author, SystemId.Unknown);
}

static addPqSignature(builder:flatbuffers.Builder, pqSignatureOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, pqSignatureOffset, 0);
}

static createPqSignatureVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPqSignatureVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endWitnessEntry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
