// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

/**
 * XXH3-128 content digest (16 bytes).
 */
export class Xxh3Digest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Xxh3Digest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

lo():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

hi():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createXxh3Digest(builder:flatbuffers.Builder, lo: bigint, hi: bigint):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeInt64(BigInt(hi ?? 0));
  builder.writeInt64(BigInt(lo ?? 0));
  return builder.offset();
}

}
