// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Policy decision for an incoming security request.
 */
export enum PolicyDecision {
  Allow = 0,
  Deny = 1,
  Challenge = 2,
  Quarantine = 3
}
