// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

/**
 * Probabilistic fingerprint bucket array (32 bytes = 4 × uint64).
 * Used for constant-time membership checking without dynamic memory.
 */
export class ProbabilisticFingerprint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProbabilisticFingerprint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

bucket0():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

bucket1():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

bucket2():bigint {
  return this.bb!.readUint64(this.bb_pos + 16);
}

bucket3():bigint {
  return this.bb!.readUint64(this.bb_pos + 24);
}

static sizeOf():number {
  return 32;
}

static createProbabilisticFingerprint(builder:flatbuffers.Builder, bucket0: bigint, bucket1: bigint, bucket2: bigint, bucket3: bigint):flatbuffers.Offset {
  builder.prep(8, 32);
  builder.writeInt64(BigInt(bucket3 ?? 0));
  builder.writeInt64(BigInt(bucket2 ?? 0));
  builder.writeInt64(BigInt(bucket1 ?? 0));
  builder.writeInt64(BigInt(bucket0 ?? 0));
  return builder.offset();
}

}
