// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DomainContext } from '../../mothership/common/domain-context.js';
import { ProvenanceRecord } from '../../mothership/common/provenance-record.js';
import { Xxh3Digest } from '../../mothership/common/xxh3-digest.js';
import { ProbabilisticFingerprint } from '../../mothership/wasm-gate/probabilistic-fingerprint.js';


/**
 * Inbound security evaluation request.
 * The caller_did field holds a DID document hash (variable-length; DID formats differ).
 * The domain_context enables the gate to tag the request's semantic domain for
 * downstream threat-intelligence transfer by System 2.
 */
export class SecurityRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SecurityRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSecurityRequest(bb:flatbuffers.ByteBuffer, obj?:SecurityRequest):SecurityRequest {
  return (obj || new SecurityRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSecurityRequest(bb:flatbuffers.ByteBuffer, obj?:SecurityRequest):SecurityRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SecurityRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

callerDid(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

callerDidLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

callerDidArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

payloadDigest(obj?:Xxh3Digest):Xxh3Digest|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Xxh3Digest()).__init(this.bb_pos + offset, this.bb!) : null;
}

provenance(obj?:ProvenanceRecord):ProvenanceRecord|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ProvenanceRecord()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

domainContext(obj?:DomainContext):DomainContext|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new DomainContext()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

fingerprint(obj?:ProbabilisticFingerprint):ProbabilisticFingerprint|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new ProbabilisticFingerprint()).__init(this.bb_pos + offset, this.bb!) : null;
}

timestampNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startSecurityRequest(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addRequestId(builder:flatbuffers.Builder, requestId:bigint) {
  builder.addFieldInt64(0, requestId, BigInt('0'));
}

static addCallerDid(builder:flatbuffers.Builder, callerDidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, callerDidOffset, 0);
}

static createCallerDidVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startCallerDidVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addPayloadDigest(builder:flatbuffers.Builder, payloadDigestOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, payloadDigestOffset, 0);
}

static addProvenance(builder:flatbuffers.Builder, provenanceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, provenanceOffset, 0);
}

static addDomainContext(builder:flatbuffers.Builder, domainContextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, domainContextOffset, 0);
}

static addFingerprint(builder:flatbuffers.Builder, fingerprintOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, fingerprintOffset, 0);
}

static addTimestampNs(builder:flatbuffers.Builder, timestampNs:bigint) {
  builder.addFieldInt64(6, timestampNs, BigInt('0'));
}

static endSecurityRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishSecurityRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedSecurityRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

}
