// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DomainContext } from '../../mothership/common/domain-context.js';
import { ProvenanceRecord } from '../../mothership/common/provenance-record.js';
import { ThreatLevel } from '../../mothership/common/threat-level.js';
import { WitnessEntry } from '../../mothership/common/witness-entry.js';
import { PolicyDecision } from '../../mothership/wasm-gate/policy-decision.js';


/**
 * Outbound security evaluation response.
 * reasoning_code is a compact internal status code; no string allocation in WASM.
 * The witness_entry appends this decision to the RVF Witness Chain.
 */
export class SecurityResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SecurityResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSecurityResponse(bb:flatbuffers.ByteBuffer, obj?:SecurityResponse):SecurityResponse {
  return (obj || new SecurityResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSecurityResponse(bb:flatbuffers.ByteBuffer, obj?:SecurityResponse):SecurityResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SecurityResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

decision():PolicyDecision {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PolicyDecision.Allow;
}

threatLevel():ThreatLevel {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ThreatLevel.None;
}

provenance(obj?:ProvenanceRecord):ProvenanceRecord|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ProvenanceRecord()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

domainContext(obj?:DomainContext):DomainContext|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new DomainContext()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

reasoningCode():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

processingNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

witnessEntry(obj?:WitnessEntry):WitnessEntry|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new WitnessEntry()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSecurityResponse(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addRequestId(builder:flatbuffers.Builder, requestId:bigint) {
  builder.addFieldInt64(0, requestId, BigInt('0'));
}

static addDecision(builder:flatbuffers.Builder, decision:PolicyDecision) {
  builder.addFieldInt8(1, decision, PolicyDecision.Allow);
}

static addThreatLevel(builder:flatbuffers.Builder, threatLevel:ThreatLevel) {
  builder.addFieldInt8(2, threatLevel, ThreatLevel.None);
}

static addProvenance(builder:flatbuffers.Builder, provenanceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, provenanceOffset, 0);
}

static addDomainContext(builder:flatbuffers.Builder, domainContextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, domainContextOffset, 0);
}

static addReasoningCode(builder:flatbuffers.Builder, reasoningCode:number) {
  builder.addFieldInt16(5, reasoningCode, 0);
}

static addProcessingNs(builder:flatbuffers.Builder, processingNs:bigint) {
  builder.addFieldInt64(6, processingNs, BigInt('0'));
}

static addWitnessEntry(builder:flatbuffers.Builder, witnessEntryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, witnessEntryOffset, 0);
}

static endSecurityResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
