// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DomainContext } from '../../mothership/common/domain-context.js';
import { ProvenanceRecord } from '../../mothership/common/provenance-record.js';
import { ProbabilisticFingerprint } from '../../mothership/wasm-gate/probabilistic-fingerprint.js';


/**
 * Signature update pushed by System 2 to patch System 1's fingerprint model.
 * This is the only mechanism by which System 1 "learns" — always externally driven.
 * The domain_context indicates which threat domain prompted this update.
 */
export class SignatureUpdate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SignatureUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSignatureUpdate(bb:flatbuffers.ByteBuffer, obj?:SignatureUpdate):SignatureUpdate {
  return (obj || new SignatureUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSignatureUpdate(bb:flatbuffers.ByteBuffer, obj?:SignatureUpdate):SignatureUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SignatureUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

updateId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

newSignatures(index: number, obj?:ProbabilisticFingerprint):ProbabilisticFingerprint|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ProbabilisticFingerprint()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 32, this.bb!) : null;
}

newSignaturesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

domainContext(obj?:DomainContext):DomainContext|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new DomainContext()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

provenance(obj?:ProvenanceRecord):ProvenanceRecord|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ProvenanceRecord()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

appliedHeight():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startSignatureUpdate(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addUpdateId(builder:flatbuffers.Builder, updateId:bigint) {
  builder.addFieldInt64(0, updateId, BigInt('0'));
}

static addNewSignatures(builder:flatbuffers.Builder, newSignaturesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, newSignaturesOffset, 0);
}

static startNewSignaturesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(32, numElems, 8);
}

static addDomainContext(builder:flatbuffers.Builder, domainContextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, domainContextOffset, 0);
}

static addProvenance(builder:flatbuffers.Builder, provenanceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, provenanceOffset, 0);
}

static addAppliedHeight(builder:flatbuffers.Builder, appliedHeight:bigint) {
  builder.addFieldInt64(4, appliedHeight, BigInt('0'));
}

static endSignatureUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
