#![allow(warnings)]
// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use crate::common_generated::*;
use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod mothership {
  pub use crate::common_generated::mothership::common;

  use crate::common_generated::*;
  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod rpc {

  use crate::common_generated::*;
  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_RPC_DIRECTION: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_RPC_DIRECTION: u8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_RPC_DIRECTION: [RpcDirection; 2] = [
  RpcDirection::WasmToUnix,
  RpcDirection::UnixToWasm,
];

/// Direction of a cross-boundary call.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct RpcDirection(pub u8);
#[allow(non_upper_case_globals)]
impl RpcDirection {
  pub const WasmToUnix: Self = Self(0);
  pub const UnixToWasm: Self = Self(1);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::WasmToUnix,
    Self::UnixToWasm,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::WasmToUnix => Some("WasmToUnix"),
      Self::UnixToWasm => Some("UnixToWasm"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for RpcDirection {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for RpcDirection {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for RpcDirection {
    type Output = RpcDirection;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for RpcDirection {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for RpcDirection {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for RpcDirection {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_RPC_METHOD: u16 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_RPC_METHOD: u16 = 202;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_RPC_METHOD: [RpcMethod; 11] = [
  RpcMethod::Unknown,
  RpcMethod::ReportThreat,
  RpcMethod::RequestPolicyQuery,
  RpcMethod::RequestPatch,
  RpcMethod::LogWitnessEntry,
  RpcMethod::PushSignatureUpdate,
  RpcMethod::PushPolicyUpdate,
  RpcMethod::FlushFingerprints,
  RpcMethod::EscalateToGateway,
  RpcMethod::AuditLog,
  RpcMethod::DomainTransferRequest,
];

/// Compact method identifier replaces string-based method names (no heap alloc in WASM).
/// Ranges:   1–99   System 1 → Unix outbound calls
///           100–199 System 2 patches into System 1
///           200–299 Escalation path to System 3
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct RpcMethod(pub u16);
#[allow(non_upper_case_globals)]
impl RpcMethod {
  pub const Unknown: Self = Self(0);
  pub const ReportThreat: Self = Self(1);
  pub const RequestPolicyQuery: Self = Self(2);
  pub const RequestPatch: Self = Self(3);
  pub const LogWitnessEntry: Self = Self(4);
  pub const PushSignatureUpdate: Self = Self(100);
  pub const PushPolicyUpdate: Self = Self(101);
  pub const FlushFingerprints: Self = Self(102);
  pub const EscalateToGateway: Self = Self(200);
  pub const AuditLog: Self = Self(201);
  pub const DomainTransferRequest: Self = Self(202);

  pub const ENUM_MIN: u16 = 0;
  pub const ENUM_MAX: u16 = 202;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Unknown,
    Self::ReportThreat,
    Self::RequestPolicyQuery,
    Self::RequestPatch,
    Self::LogWitnessEntry,
    Self::PushSignatureUpdate,
    Self::PushPolicyUpdate,
    Self::FlushFingerprints,
    Self::EscalateToGateway,
    Self::AuditLog,
    Self::DomainTransferRequest,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Unknown => Some("Unknown"),
      Self::ReportThreat => Some("ReportThreat"),
      Self::RequestPolicyQuery => Some("RequestPolicyQuery"),
      Self::RequestPatch => Some("RequestPatch"),
      Self::LogWitnessEntry => Some("LogWitnessEntry"),
      Self::PushSignatureUpdate => Some("PushSignatureUpdate"),
      Self::PushPolicyUpdate => Some("PushPolicyUpdate"),
      Self::FlushFingerprints => Some("FlushFingerprints"),
      Self::EscalateToGateway => Some("EscalateToGateway"),
      Self::AuditLog => Some("AuditLog"),
      Self::DomainTransferRequest => Some("DomainTransferRequest"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for RpcMethod {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for RpcMethod {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u16>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for RpcMethod {
    type Output = RpcMethod;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u16>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for RpcMethod {
  type Scalar = u16;
  #[inline]
  fn to_little_endian(self) -> u16 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u16) -> Self {
    let b = u16::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for RpcMethod {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u16::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for RpcMethod {}
pub enum RpcCallRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Outbound RPC call envelope. The payload field carries a nested FlatBuffers
/// message appropriate to the method (e.g. SecurityRequest, ThreatReport).
pub struct RpcCallRequest<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RpcCallRequest<'a> {
  type Inner = RpcCallRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RpcCallRequest<'a> {
  pub const VT_CALL_ID: flatbuffers::VOffsetT = 4;
  pub const VT_METHOD: flatbuffers::VOffsetT = 6;
  pub const VT_DIRECTION: flatbuffers::VOffsetT = 8;
  pub const VT_PAYLOAD: flatbuffers::VOffsetT = 10;
  pub const VT_PROVENANCE: flatbuffers::VOffsetT = 12;
  pub const VT_DEADLINE_NS: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RpcCallRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RpcCallRequestArgs<'args>
  ) -> flatbuffers::WIPOffset<RpcCallRequest<'bldr>> {
    let mut builder = RpcCallRequestBuilder::new(_fbb);
    builder.add_deadline_ns(args.deadline_ns);
    builder.add_call_id(args.call_id);
    if let Some(x) = args.provenance { builder.add_provenance(x); }
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_method(args.method);
    builder.add_direction(args.direction);
    builder.finish()
  }


  #[inline]
  pub fn call_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RpcCallRequest::VT_CALL_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn method(&self) -> RpcMethod {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RpcMethod>(RpcCallRequest::VT_METHOD, Some(RpcMethod::Unknown)).unwrap()}
  }
  #[inline]
  pub fn direction(&self) -> RpcDirection {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RpcDirection>(RpcCallRequest::VT_DIRECTION, Some(RpcDirection::WasmToUnix)).unwrap()}
  }
  #[inline]
  pub fn payload(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(RpcCallRequest::VT_PAYLOAD, None)}
  }
  #[inline]
  pub fn provenance(&self) -> Option<super::common::ProvenanceRecord<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::common::ProvenanceRecord>>(RpcCallRequest::VT_PROVENANCE, None)}
  }
  #[inline]
  pub fn deadline_ns(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RpcCallRequest::VT_DEADLINE_NS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for RpcCallRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("call_id", Self::VT_CALL_ID, false)?
     .visit_field::<RpcMethod>("method", Self::VT_METHOD, false)?
     .visit_field::<RpcDirection>("direction", Self::VT_DIRECTION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("payload", Self::VT_PAYLOAD, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::common::ProvenanceRecord>>("provenance", Self::VT_PROVENANCE, false)?
     .visit_field::<u64>("deadline_ns", Self::VT_DEADLINE_NS, false)?
     .finish();
    Ok(())
  }
}
pub struct RpcCallRequestArgs<'a> {
    pub call_id: u64,
    pub method: RpcMethod,
    pub direction: RpcDirection,
    pub payload: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub provenance: Option<flatbuffers::WIPOffset<super::common::ProvenanceRecord<'a>>>,
    pub deadline_ns: u64,
}
impl<'a> Default for RpcCallRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    RpcCallRequestArgs {
      call_id: 0,
      method: RpcMethod::Unknown,
      direction: RpcDirection::WasmToUnix,
      payload: None,
      provenance: None,
      deadline_ns: 0,
    }
  }
}

pub struct RpcCallRequestBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RpcCallRequestBuilder<'a, 'b> {
  #[inline]
  pub fn add_call_id(&mut self, call_id: u64) {
    self.fbb_.push_slot::<u64>(RpcCallRequest::VT_CALL_ID, call_id, 0);
  }
  #[inline]
  pub fn add_method(&mut self, method: RpcMethod) {
    self.fbb_.push_slot::<RpcMethod>(RpcCallRequest::VT_METHOD, method, RpcMethod::Unknown);
  }
  #[inline]
  pub fn add_direction(&mut self, direction: RpcDirection) {
    self.fbb_.push_slot::<RpcDirection>(RpcCallRequest::VT_DIRECTION, direction, RpcDirection::WasmToUnix);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RpcCallRequest::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn add_provenance(&mut self, provenance: flatbuffers::WIPOffset<super::common::ProvenanceRecord<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::common::ProvenanceRecord>>(RpcCallRequest::VT_PROVENANCE, provenance);
  }
  #[inline]
  pub fn add_deadline_ns(&mut self, deadline_ns: u64) {
    self.fbb_.push_slot::<u64>(RpcCallRequest::VT_DEADLINE_NS, deadline_ns, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RpcCallRequestBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RpcCallRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RpcCallRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RpcCallRequest<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RpcCallRequest");
      ds.field("call_id", &self.call_id());
      ds.field("method", &self.method());
      ds.field("direction", &self.direction());
      ds.field("payload", &self.payload());
      ds.field("provenance", &self.provenance());
      ds.field("deadline_ns", &self.deadline_ns());
      ds.finish()
  }
}
pub enum RpcCallResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Response envelope. The call_id echoes the originating request.
pub struct RpcCallResponse<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RpcCallResponse<'a> {
  type Inner = RpcCallResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RpcCallResponse<'a> {
  pub const VT_CALL_ID: flatbuffers::VOffsetT = 4;
  pub const VT_STATUS: flatbuffers::VOffsetT = 6;
  pub const VT_PAYLOAD: flatbuffers::VOffsetT = 8;
  pub const VT_PROVENANCE: flatbuffers::VOffsetT = 10;
  pub const VT_LATENCY_NS: flatbuffers::VOffsetT = 12;
  pub const VT_ERROR_CODE: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RpcCallResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RpcCallResponseArgs<'args>
  ) -> flatbuffers::WIPOffset<RpcCallResponse<'bldr>> {
    let mut builder = RpcCallResponseBuilder::new(_fbb);
    builder.add_latency_ns(args.latency_ns);
    builder.add_call_id(args.call_id);
    if let Some(x) = args.provenance { builder.add_provenance(x); }
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_error_code(args.error_code);
    builder.add_status(args.status);
    builder.finish()
  }


  #[inline]
  pub fn call_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RpcCallResponse::VT_CALL_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn status(&self) -> super::common::RequestStatus {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<super::common::RequestStatus>(RpcCallResponse::VT_STATUS, Some(super::common::RequestStatus::Pending)).unwrap()}
  }
  #[inline]
  pub fn payload(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(RpcCallResponse::VT_PAYLOAD, None)}
  }
  #[inline]
  pub fn provenance(&self) -> Option<super::common::ProvenanceRecord<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<super::common::ProvenanceRecord>>(RpcCallResponse::VT_PROVENANCE, None)}
  }
  #[inline]
  pub fn latency_ns(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RpcCallResponse::VT_LATENCY_NS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn error_code(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(RpcCallResponse::VT_ERROR_CODE, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for RpcCallResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("call_id", Self::VT_CALL_ID, false)?
     .visit_field::<super::common::RequestStatus>("status", Self::VT_STATUS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("payload", Self::VT_PAYLOAD, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<super::common::ProvenanceRecord>>("provenance", Self::VT_PROVENANCE, false)?
     .visit_field::<u64>("latency_ns", Self::VT_LATENCY_NS, false)?
     .visit_field::<u16>("error_code", Self::VT_ERROR_CODE, false)?
     .finish();
    Ok(())
  }
}
pub struct RpcCallResponseArgs<'a> {
    pub call_id: u64,
    pub status: super::common::RequestStatus,
    pub payload: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub provenance: Option<flatbuffers::WIPOffset<super::common::ProvenanceRecord<'a>>>,
    pub latency_ns: u64,
    pub error_code: u16,
}
impl<'a> Default for RpcCallResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    RpcCallResponseArgs {
      call_id: 0,
      status: super::common::RequestStatus::Pending,
      payload: None,
      provenance: None,
      latency_ns: 0,
      error_code: 0,
    }
  }
}

pub struct RpcCallResponseBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RpcCallResponseBuilder<'a, 'b> {
  #[inline]
  pub fn add_call_id(&mut self, call_id: u64) {
    self.fbb_.push_slot::<u64>(RpcCallResponse::VT_CALL_ID, call_id, 0);
  }
  #[inline]
  pub fn add_status(&mut self, status: super::common::RequestStatus) {
    self.fbb_.push_slot::<super::common::RequestStatus>(RpcCallResponse::VT_STATUS, status, super::common::RequestStatus::Pending);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RpcCallResponse::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn add_provenance(&mut self, provenance: flatbuffers::WIPOffset<super::common::ProvenanceRecord<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<super::common::ProvenanceRecord>>(RpcCallResponse::VT_PROVENANCE, provenance);
  }
  #[inline]
  pub fn add_latency_ns(&mut self, latency_ns: u64) {
    self.fbb_.push_slot::<u64>(RpcCallResponse::VT_LATENCY_NS, latency_ns, 0);
  }
  #[inline]
  pub fn add_error_code(&mut self, error_code: u16) {
    self.fbb_.push_slot::<u16>(RpcCallResponse::VT_ERROR_CODE, error_code, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RpcCallResponseBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RpcCallResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RpcCallResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RpcCallResponse<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RpcCallResponse");
      ds.field("call_id", &self.call_id());
      ds.field("status", &self.status());
      ds.field("payload", &self.payload());
      ds.field("provenance", &self.provenance());
      ds.field("latency_ns", &self.latency_ns());
      ds.field("error_code", &self.error_code());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `RpcCallRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rpc_call_request_unchecked`.
pub fn root_as_rpc_call_request(buf: &[u8]) -> Result<RpcCallRequest, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<RpcCallRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `RpcCallRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_rpc_call_request_unchecked`.
pub fn size_prefixed_root_as_rpc_call_request(buf: &[u8]) -> Result<RpcCallRequest, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<RpcCallRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `RpcCallRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rpc_call_request_unchecked`.
pub fn root_as_rpc_call_request_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RpcCallRequest<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<RpcCallRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `RpcCallRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rpc_call_request_unchecked`.
pub fn size_prefixed_root_as_rpc_call_request_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RpcCallRequest<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<RpcCallRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a RpcCallRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `RpcCallRequest`.
pub unsafe fn root_as_rpc_call_request_unchecked(buf: &[u8]) -> RpcCallRequest {
  flatbuffers::root_unchecked::<RpcCallRequest>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed RpcCallRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `RpcCallRequest`.
pub unsafe fn size_prefixed_root_as_rpc_call_request_unchecked(buf: &[u8]) -> RpcCallRequest {
  flatbuffers::size_prefixed_root_unchecked::<RpcCallRequest>(buf)
}
#[inline]
pub fn finish_rpc_call_request_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<RpcCallRequest<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_rpc_call_request_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<RpcCallRequest<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod rpc
}  // pub mod mothership

